name: R Package CI

on:
  push:
    branches:
      - main

jobs:
  setup-r:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.3'

    - name: Verify R Version
      run: R --version

    - name: Install Package Dependencies
      run: |
        R -e 'install.packages("devtools")'
        R -e 'devtools::install_deps(dependencies = TRUE)'

