name: R Package CI

on:
  push:
    branches:
      - main

jobs:
  setup-r:
     runs-on: macos-latest
#    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.3'

    - name: Verify R Version
      run: R --version

#    - name: Install devtools dependencies
#      run: |
#        R -e 'install.packages(c("usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker"))'

    - name: Install Devtools and its Dependencies
      run: |
        R -e 'install.packages("devtools")'
        R -e 'devtools::install_deps(dependencies = TRUE)'

