name: R Package CI

on:
  push:
    branches:
      - main

jobs:
  setup-r:
    runs-on: macos-latest
#    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.3'

    - name: Verify R Version
      run: R --version

#    - name: Install devtools dependencies
#      run: |
#        R -e 'install.packages(c("usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker"))'

#ok    - name: Install Devtools and its Dependencies
#ok      run: |
#ok        R -e 'install.packages("devtools")'
#        R -e 'devtools::install_deps(dependencies = TRUE)'

    - name: Install lintr and testthat
      run: R -e 'install.packages(c("lintr", "testthat", "remotes"))'

    - name: Verify Packages
      run: |
      R -e 'library(testthat)'
      R -e 'library(lintr)'
#        R -e 'packageVersion("devtools")'
#        R -e 'library(devtools)'
      R -e 'packageVersion("testthat")'
      R -e 'packageVersion("lintr")'
#        R -e 'devtools::test()'

    - name: Run Unit Tests
      run: R -e 'testthat::test_dir("tests")'
