name: Create and Merge Pull Request

on:
  push:
    branches:
      - feature/Update-analysis

jobs:
  create_and_merge_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          git checkout -b feature/Update-analysis
          git add .
          git commit -m "New feature added"
          git push origin feature/Update-analysis
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}

      - name: Merge Pull Request
        uses: actions/github-script@0.7.0
        with:
          github-token: ${{ secrets.G_TOKEN }}
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const pullRequest = pullRequests.find(pr => pr.head.ref === 'feature/Update-analysis');
            if (!pullRequest) {
              core.setFailed('Pull request not found');
              return;
            }

            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequest.number
            });
